var itemProperty = ["PageKey", "PanelKey", "ParentItemKey", "Key", "DataKey",
    "Style", "Edit", "IsSelectable", "IsPrintable", "X",
    "Y", "Width", "Height", "Angle", "BackColor",
    "BackImageString", "BorderColor", "BorderWidth", "BorderDash", "InLineStyle",
    "InLineColor", "InLineDash", "InLineWidth", "InLineCap", "Checked",
    "CheckGroup", "CheckBoxStyle", "CheckBoxAlign", "CheckBoxColor", "CheckBoxWidth",
    "CheckBoxHeight", "CheckBoxLineWidth", "CheckStyle", "CheckValue", "CheckForeColor",
    "CheckBackColor", "CheckLineWidth", "UnCheckStyle", "UnCheckValue", "UnCheckForeColor",
    "UnCheckBackColor", "UnCheckLineWidth", "TextFont", "TextColor", "TextAlign",
    "TextLineSpacing", "TextBorder", "TextMaxLine", "IsViewOutBound", "IsViewText",
    "IsVisible", "IsBorderLeft", "IsBorderRight", "IsBorderTop", "IsBorderBottom",
    "IsUserSizable", "ChangeHeightItem", "ChangeTopItem", "TextFormat", "EditOnly",
    "ClickLeft", "ClickRight", "ChangedValue", "TabFrom", "TabTo",
    "TabEnterFrom", "TabEnterTo", "IsIncomplete", "IncompleteKey", "IsWrap",
    "CheckText", "UnCheckText", "Text"];